<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCHU42lw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCHU42lw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCHU42lw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCHU42lw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCHU42lw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CHU42lw',
    'container.build_id' => '5152f726',
    'container.build_time' => 1675661846,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCHU42lw');
